version: "3.9"
services:
  test:
    build:
      discounts-applier
    environment:
      MONGO_URI: "mongodb://user:pass@mongo:27017"
    ports:
      - 8080:8080
    networks:
      - db
    entrypoint: >
      sh -c "./writer &&
             ./api test"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/
    networks:
      - db
    depends_on:
      - mongo
networks:
  db:
