// Code generated by ifacemaker; DO NOT EDIT.

package products

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/mongo/readconcern"
	"go.mongodb.org/mongo-driver/mongo/readpref"
	"go.mongodb.org/mongo-driver/mongo/writeconcern"
)

// MongoDB ...
type MongoDB interface {
	// Client returns the Client the Database was created from.
	Client() *mongo.Client
	// Name returns the name of the database.
	Name() string
	// Collection gets a handle for a collection with the given name configured with the given CollectionOptions.
	Collection(name string, opts ...*options.CollectionOptions) *mongo.Collection
	// Aggregate executes an aggregate command the database. This requires MongoDB version >= 3.6 and driver version >=
	// 1.1.0.
	//
	// The pipeline parameter must be a slice of documents, each representing an aggregation stage. The pipeline
	// cannot be nil but can be empty. The stage documents must all be non-nil. For a pipeline of bson.D documents, the
	// mongo.Pipeline type can be used. See
	// https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/#db-aggregate-stages for a list of valid
	// stages in database-level aggregations.
	//
	// The opts parameter can be used to specify options for this operation (see the options.AggregateOptions documentation).
	//
	// For more information about the command, see https://docs.mongodb.com/manual/reference/command/aggregate/.
	Aggregate(ctx context.Context, pipeline interface{}, opts ...*options.AggregateOptions) (*mongo.Cursor, error)
	// RunCommand executes the given command against the database. This function does not obey the Database's read
	// preference. To specify a read preference, the RunCmdOptions.ReadPreference option must be used.
	//
	// The runCommand parameter must be a document for the command to be executed. It cannot be nil.
	// This must be an order-preserving type such as bson.D. Map types such as bson.M are not valid.
	// If the command document contains a session ID or any transaction-specific fields, the behavior is undefined.
	// Specifying API versioning options in the command document and declaring an API version on the client is not supported.
	// The behavior of RunCommand is undefined in this case.
	//
	// The opts parameter can be used to specify options for this operation (see the options.RunCmdOptions documentation).
	RunCommand(ctx context.Context, runCommand interface{}, opts ...*options.RunCmdOptions) *mongo.SingleResult
	// RunCommandCursor executes the given command against the database and parses the response as a cursor. If the command
	// being executed does not return a cursor (e.g. insert), the command will be executed on the server and an error will
	// be returned because the server response cannot be parsed as a cursor. This function does not obey the Database's read
	// preference. To specify a read preference, the RunCmdOptions.ReadPreference option must be used.
	//
	// The runCommand parameter must be a document for the command to be executed. It cannot be nil.
	// This must be an order-preserving type such as bson.D. Map types such as bson.M are not valid.
	// If the command document contains a session ID or any transaction-specific fields, the behavior is undefined.
	//
	// The opts parameter can be used to specify options for this operation (see the options.RunCmdOptions documentation).
	RunCommandCursor(ctx context.Context, runCommand interface{}, opts ...*options.RunCmdOptions) (*mongo.Cursor, error)
	// Drop drops the database on the server. This method ignores "namespace not found" errors so it is safe to drop
	// a database that does not exist on the server.
	Drop(ctx context.Context) error
	// ListCollectionSpecifications executes a listCollections command and returns a slice of CollectionSpecification
	// instances representing the collections in the database.
	//
	// The filter parameter must be a document containing query operators and can be used to select which collections
	// are included in the result. It cannot be nil. An empty document (e.g. bson.D{}) should be used to include all
	// collections.
	//
	// The opts parameter can be used to specify options for the operation (see the options.ListCollectionsOptions
	// documentation).
	//
	// For more information about the command, see https://docs.mongodb.com/manual/reference/command/listCollections/.
	ListCollectionSpecifications(ctx context.Context, filter interface{}, opts ...*options.ListCollectionsOptions) ([]*mongo.CollectionSpecification, error)
	// ListCollections executes a listCollections command and returns a cursor over the collections in the database.
	//
	// The filter parameter must be a document containing query operators and can be used to select which collections
	// are included in the result. It cannot be nil. An empty document (e.g. bson.D{}) should be used to include all
	// collections.
	//
	// The opts parameter can be used to specify options for the operation (see the options.ListCollectionsOptions
	// documentation).
	//
	// For more information about the command, see https://docs.mongodb.com/manual/reference/command/listCollections/.
	ListCollections(ctx context.Context, filter interface{}, opts ...*options.ListCollectionsOptions) (*mongo.Cursor, error)
	// ListCollectionNames executes a listCollections command and returns a slice containing the names of the collections
	// in the database. This method requires driver version >= 1.1.0.
	//
	// The filter parameter must be a document containing query operators and can be used to select which collections
	// are included in the result. It cannot be nil. An empty document (e.g. bson.D{}) should be used to include all
	// collections.
	//
	// The opts parameter can be used to specify options for the operation (see the options.ListCollectionsOptions
	// documentation).
	//
	// For more information about the command, see https://docs.mongodb.com/manual/reference/command/listCollections/.
	ListCollectionNames(ctx context.Context, filter interface{}, opts ...*options.ListCollectionsOptions) ([]string, error)
	// ReadConcern returns the read concern used to configure the Database object.
	ReadConcern() *readconcern.ReadConcern
	// ReadPreference returns the read preference used to configure the Database object.
	ReadPreference() *readpref.ReadPref
	// WriteConcern returns the write concern used to configure the Database object.
	WriteConcern() *writeconcern.WriteConcern
	// Watch returns a change stream for all changes to the corresponding database. See
	// https://docs.mongodb.com/manual/changeStreams/ for more information about change streams.
	//
	// The Database must be configured with read concern majority or no read concern for a change stream to be created
	// successfully.
	//
	// The pipeline parameter must be a slice of documents, each representing a pipeline stage. The pipeline cannot be
	// nil but can be empty. The stage documents must all be non-nil. See https://docs.mongodb.com/manual/changeStreams/ for
	// a list of pipeline stages that can be used with change streams. For a pipeline of bson.D documents, the
	// mongo.Pipeline{} type can be used.
	//
	// The opts parameter can be used to specify options for change stream creation (see the options.ChangeStreamOptions
	// documentation).
	Watch(ctx context.Context, pipeline interface{}, opts ...*options.ChangeStreamOptions) (*mongo.ChangeStream, error)
	// CreateCollection executes a create command to explicitly create a new collection with the specified name on the
	// server. If the collection being created already exists, this method will return a mongo.CommandError. This method
	// requires driver version 1.4.0 or higher.
	//
	// The opts parameter can be used to specify options for the operation (see the options.CreateCollectionOptions
	// documentation).
	//
	// For more information about the command, see https://docs.mongodb.com/manual/reference/command/create/.
	CreateCollection(ctx context.Context, name string, opts ...*options.CreateCollectionOptions) error
	// CreateView executes a create command to explicitly create a view on the server. See
	// https://docs.mongodb.com/manual/core/views/ for more information about views. This method requires driver version >=
	// 1.4.0 and MongoDB version >= 3.4.
	//
	// The viewName parameter specifies the name of the view to create.
	//
	// The viewOn parameter specifies the name of the collection or view on which this view will be created
	//
	// The pipeline parameter specifies an aggregation pipeline that will be exececuted against the source collection or
	// view to create this view.
	//
	// The opts parameter can be used to specify options for the operation (see the options.CreateViewOptions
	// documentation).
	CreateView(ctx context.Context, viewName, viewOn string, pipeline interface{}, opts ...*options.CreateViewOptions) error
}
