// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	productsdiscounts "discounts-applier/internal/productsdiscounts"

	mock "github.com/stretchr/testify/mock"
)

// Dependencies is an autogenerated mock type for the Dependencies type
type Dependencies struct {
	mock.Mock
}

// GetProductsDiscounts provides a mock function with given fields:
func (_m *Dependencies) GetProductsDiscounts() productsdiscounts.Manager {
	ret := _m.Called()

	var r0 productsdiscounts.Manager
	if rf, ok := ret.Get(0).(func() productsdiscounts.Manager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(productsdiscounts.Manager)
		}
	}

	return r0
}
