// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	discounts "discounts-applier/internal/productsdiscounts/discounts"

	mock "github.com/stretchr/testify/mock"

	products "discounts-applier/internal/productsdiscounts/products"
)

// DiscountApplier is an autogenerated mock type for the DiscountApplier type
type DiscountApplier struct {
	mock.Mock
}

// ApplyToList provides a mock function with given fields: _a0
func (_m *DiscountApplier) ApplyToList(_a0 []products.Product) []discounts.Product {
	ret := _m.Called(_a0)

	var r0 []discounts.Product
	if rf, ok := ret.Get(0).(func([]products.Product) []discounts.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]discounts.Product)
		}
	}

	return r0
}
