// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	discounts "discounts-applier/internal/productsdiscounts/discounts"

	mock "github.com/stretchr/testify/mock"

	products "discounts-applier/internal/productsdiscounts/products"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetProductsWithDiscount provides a mock function with given fields: filters
func (_m *Manager) GetProductsWithDiscount(filters ...products.Filter) ([]discounts.Product, error) {
	_va := make([]interface{}, len(filters))
	for _i := range filters {
		_va[_i] = filters[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []discounts.Product
	if rf, ok := ret.Get(0).(func(...products.Filter) []discounts.Product); ok {
		r0 = rf(filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]discounts.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...products.Filter) error); ok {
		r1 = rf(filters...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
