// Code generated by mockery 2.9.4. DO NOT EDIT.

package dependencies

import (
	discounts "discounts-applier/internal/discounts"

	mock "github.com/stretchr/testify/mock"
)

// MockDependencies is an autogenerated mock type for the Dependencies type
type MockDependencies struct {
	mock.Mock
}

// GetDiscountsManager provides a mock function with given fields:
func (_m *MockDependencies) GetDiscountsManager() (discounts.Manager, error) {
	ret := _m.Called()

	var r0 discounts.Manager
	if rf, ok := ret.Get(0).(func() discounts.Manager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discounts.Manager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
